"""
Seed blog list for the MIR crawler.

Real, known-active Tumblr blogs organised by genre.
Pass to Crawler.crawl(seed_blogs=SEED_BLOGS) to bootstrap CrawlState.
Discovery from reblog chains will expand the corpus automatically after
the first run.
"""
from __future__ import annotations

SEED_BLOGS_BY_GENRE: dict[str, list[str]] = {
    "art_design": [
        "staff",
        "theartidote",
        "asylum-art",
        "itscolossal",
        "crossconnectmag",
        "artsy",
        "designspiration",
        "boingboing",
        "thisiswhyimbroke",
    ],
    "photography": [
        "photojojo",
        "natgeofound",
        "lensblr-network",
        "thephotographerssociety",
        "magnumphotos",
        "nationalgeographic",
        "500px",
        "flickr",
        "eyeem",
    ],
    "fashion_style": [
        "fashionistable",
        "wmagazine",
        "manrepeller",
        "thesartorialist",
        "fuckyeahfashioncouples",
        "vogue",
        "harpersbazaar",
        "refinery29",
        "theoutnet",
    ],
    "music": [
        "pitchfork",
        "npr-music",
        "stereogum",
        "songaday",
        "8tracks",
        "songkick",
        "bandcamp",
        "musicradar",
        "theverge",
    ],
    "writing_literature": [
        "writingpromptsworld",
        "poetryofresistance",
        "thewritingcafe",
        "wordsnquotes",
        "yeoldenews",
        "archiveofourown",
        "wattpad",
        "medium",
        "goodreads",
    ],
    "gaming": [
        "gamespot",
        "kotaku",
        "ilovevideogamessomuch",
        "pixelatedcrown",
        "theomeganerd",
        "ign",
        "polygon",
        "rockpapershotgun",
        "pcgamer",
    ],
    "anime_manga": [
        "animatedtext",
        "studioghibligifs",
        "shonenjump",
        "fuckyeahanime",
        "mangacap",
        "myanimelist",
        "crunchyroll",
        "animeplanet",
        "animenewsnetwork",
    ],
    "science_technology": [
        "nasa",
        "scishow",
        "spaceplasma",
        "neurosciencestuff",
        "thescienceofreality",
        "wired",
        "gizmodo",
        "lifehacker",
        "smithsonianmag",
    ],
    "nature_environment": [
        "earth-song",
        "theworldofphotography",
        "animalworld",
        "wildlifegifsblog",
        "oceanatdawn",
        "worldwildlife",
        "greenpeace",
        "nature",
        "bbc-earth",
    ],
    "travel": [
        "travelingcolors",
        "travelthisworld",
        "wanderlusting",
        "departured",
        "theworldlookslikethis",
        "lonelyplanet",
        "roughguides",
        "condenasttraveler",
        "nomadicmatt",
    ],
    "food_cooking": [
        "foodffs",
        "tastykitchen",
        "veganrecipeclub",
        "fullcravings",
        "yummytastyfood",
        "bonappetit",
        "foodandwine",
        "seriouseats",
        "thekitchn",
    ],
    "film_tv": [
        "cinemastatic",
        "classicfilmheroines",
        "filmforlife",
        "criterion",
        "screenmusings",
        "criterion-collection",
        "hollywoodreporter",
        "variety",
        "deadline",
    ],
    "humor_memes": [
        "tastefullyoffensive",
        "funnyordie",
        "textsfromlastnight",
        "4gifs",
        "lolsomeone",
        "failblog",
        "cheezburger",
        "memecenter",
        "ebaums",
    ],
    "history": [
        "historicaltimes",
        "thehistoryoftheworld",
        "retronaut",
        "medievalpoc",
        "oldnewyork",
        "britishmuseum",
        "metmuseum",
        "louvre",
        "britannica",
    ],
    "beauty_wellness": [
        "thelipsticklesbians",
        "reallifeskincare",
        "yogaholics",
        "fitnessgifs",
        "mindful-recovery",
        "mindbodygreen",
        "wellnessmama",
        "healthyfoodhouse",
        "fitsugar",
    ],
    "pets_animals": [
        "dailybunny",
        "cuteoverload",
        "dogsofinstaworld",
        "catsof",
        "zfrankenfluffy",
        "thepuppydogpalace",
        "barkpost",
        "thedodo",
        "animalplanet",
    ],
}

# Flat list for passing directly to Crawler.crawl()
SEED_BLOGS: list[str] = [
    blog for blogs in SEED_BLOGS_BY_GENRE.values() for blog in blogs
]
